version: '3.9'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerDBfestivos
    networks:
      - redApiFestivos
    ports:
      - "27018:27017"

networks:
  redApiFestivos:
    driver: bridge
